# Nixpacks configuration for Railway backend deployment
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm ci --omit=dev"]

[phases.build]
cmds = ["cd backend && npm run build"]

[phases.start]
cmd = "cd backend && npm run start:production"

[variables]
NODE_ENV = "production"