# Railway deployment configuration for backend service only
# Deploy backend and frontend separately

[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm run start:production"
healthcheckPath = "/health"
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
DATABASE_URL = "${{DATABASE_URL}}"
JWT_SECRET = "${{JWT_SECRET}}"
JWT_REFRESH_SECRET = "${{JWT_REFRESH_SECRET}}"

# Volume for file uploads
[[volumes]]
name = "uploads"
mountPath = "/app/backend/uploads"