# Railway deployment configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
DATABASE_URL = "${{DATABASE_URL}}"
JWT_SECRET = "${{JWT_SECRET}}"
JWT_REFRESH_SECRET = "${{JWT_REFRESH_SECRET}}"

# Volume for file uploads  
[[volumes]]
name = "uploads"
mountPath = "/app/backend/uploads"